import 'app/models/pne.dart';
import 'app/models/student.dart';

List<Student> TODOSOSESTUDANTES = [
  Student(
      name: 'NICOLE SOFIA MOTA TELES',
      id: '06sWwYRJHRwvKP3cyTL4',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'DYOGO ALVES DOS SANTOS',
      id: '0EUFGs5hq2b1ap3xAxWR',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANDRÉ SALES DE LIMA',
      id: '13SGW33bV5ZEm5khfVF4',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'HENNZO MIGUEL MEDEIROS DE MENESES',
      id: '1LXzK1sWVz4PylMZfSKq',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PEDRO HENRIQUE ALVES FERREIRA',
      id: '227JKNEvs4eRflnu2xFj',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANA BEATRIZ PAZLANDIM DE ALMEIDA',
      id: '5XvvG8e1a4zVxwQYbXZl',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'MARIA EDUARDA RODRIGUES BARBOSA',
      id: '70CAx0X5O3Spc3KCyp8d',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'MARIA FERNANDA SANTOS DAMASCENO',
      id: '92oZKrVY62ZUBXD1E4Zu',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'GUSTAVO MACHADO DE SOUSA',
      id: '9nWpaqAXvZSxlogblEGN',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'VICTOR ALMEIDA LEITE ALENCAR',
      id: 'CiQaIgsAXcI4JwiPagI9',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PEDRO HENRIQUE COSTA CORDEIRO',
      id: 'FOURExlqXoYFjqYRtYQ6',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'AUGUSTO PEREIRA CHAVES',
      id: 'Fb6YUxTrxl3mCVQWoghX',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PEDRO VICTOR DIAS DA SILVA',
      id: 'HXSH52DtIooyan5ZaHf5',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'LAISA FERNANDA DE OLIVEIRA BARBOSA',
      id: 'IJmBwa2W8d1t0l35vdAl',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'KAMILY SOPHIA MARQUES DA SILVA',
      id: 'If7VU9u8eQG33FtEHBaA',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'CARLOS FERNANDO GONÇALVES DA CONCEIÇÃO',
      id: 'J2jjI0GTadnAa2sL4HYd',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PHILLIPE ROMEU DA SILVA OLIVEIRA',
      id: 'JpVq6lzQIR9ZlzSwLgSI',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'LAIZA VITÓRIA ALVES RODRIGUES',
      id: 'KUkPNk3OM7ohDO7a4a7D',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANDERSON JOHN CABRAL DE OLIVEIRA',
      id: 'L7BmfON67rEe4g0spCam',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'RAFAELA DE SOUZA VIANA',
      id: 'PqqMAhTQzj1cIoSDa3BM',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'GEOVANNA VIEIRA DOS SANTOS',
      id: 'Q8jALdDmDJ1ls0QbEFgx',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANA BEATRIZ PEREIRA DAMASCENO',
      id: 'R6yuEAJ78ACObjq1tvzC',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'JOÃO PEDRO MARTINS BEZERRA TELES',
      id: 'R8otY1MlTDDbG6R05GBV',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ARTHUR CIQUEIRA SANTANA',
      id: 'RmMKLHsodQkyeJzLNU2F',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANNY KESSYA DO NASCIMENTO SOUZA',
      id: 'SbTgznVMlZlaE0qPDOeX',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'VINICIUS SIVALDO GONÇALVES SILVA',
      id: 'TVEweXSlzWmlDVx6bMVT',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'CINTHYA ALVES DOS SANTOS',
      id: 'U0fHzoqBJsPGO6G0kZj3',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'GABRIELA FERREIRA ALENCAR',
      id: 'XFEpylOEqkwguqv8o2Bf',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'CALEB CASTILHO DIAZ',
      id: 'XYJ8WFu0VdVmE3lrwVBr',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'GEOVANA PAIVA DA SILVA SOUZA',
      id: 'cYw4ArSI28pghhBKdglq',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'a',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANA CAROLINE DE ASSIS MARQUES',
      id: 'dKlNOfcv2EvEoAE8DQDa',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'RUAN CARLOS DE FREITAS MALAQUIAS',
      id: 'ftQi0iqvDUHfV3aB5XEF',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'LAURA JENNIFER BRITO GOMES',
      id: 'g0jGc8vyvMt3WujLhk0E',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'MIGUEL MACEDO DUARTE',
      id: 'hogy9foDZvMgtwzWXNer',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANDRESSA NUNES OLIVEIRA',
      id: 'jZwkUTrht5zXViPVFBce',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PEDRO HENRIQUE RODRIGUES DE SOUSA',
      id: 'kRzLQuoiqJaRhGsp2hZy',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'HENRIQUE MACHADO DE SOUSA',
      id: 'kpXKodb6qULMizwggq22',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'MARIA LUIZA DE OLIVEIRA DOS SANTOS',
      id: 'mFL1k3niFxSOWOngV07r',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'HELOÍSA BRITO GOMES',
      id: 'mnZDMmL5Th2dFmCJfwow',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ANA PAULA LEYVA PAVON',
      id: 'oHADwHcGPQAPbAylxvyk',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'SAMUEL FLORENÇA ALVES',
      id: 'omJGy5lpuSo7GioLVSNZ',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'KAROL ANNE NUNES GONÇALVES',
      id: 'q5nChpXcQwdzlxrGjKUA',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'DEYVID RYAN RODRIGUES DE ALMEIDA',
      id: 'qUXU6Z42V7B84PHYG223',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'DAVI LUCAS GUIMARÃES MONTEIRO',
      id: 'rGy365qxMEYGzIH9bqIy',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'PAULO EMANUEL PAIVA DE JESUS',
      id: 'st2q1MJShQBlCaqCp4kf',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'ARTHUR GOMES DA SILVA',
      id: 't1h0WOKL1ogYEayIQ7pd',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'EMILLY VITÓRIA RODRIGUES DOS SANTOS',
      id: 'tdOW6u7qHlaFdb27I6AE',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'DAVY MIGUEL MACEDO DA SILVA',
      id: 'ulSboBgvd3OVET36N0YF',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'CATARINA SILVA RODRIGUES DE SOUSA',
      id: 'uunwX1IbPTY0kaas94te',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'VICTOR HUGO COSTA DE AGUIAR ALCANTARA',
      id: 'xyGVpGSfaEReCCPCLqLZ',
      imageUrl: '',
      ieducar: '1',
      level: 'FUNDAMENTAL',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: '1',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
  Student(
      name: 'KALEBY NUNES DE SANTANA',
      id: 'y7giBcJwThMa1uNIDq1b',
      imageUrl: '',
      ieducar: 'ieducar',
      level: 'level',
      schoolId: 'jxKuqXpdVQL6dbWyCVOC',
      cpf: '00000000000',
      itineraryId: 'kVFLWJsV2imAsvMKzW27',
      requiresGuardian: false,
      pne: PNE(type: PneType.none),
      residenceType: 'URBANA',
      authorized: false,
      classroomGrade: 'grade',
      attendance: [],
      createdAt: DateTime.now(),
      incidentsId: []),
];
