// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCb-LryHToHl6bBkgA8TutoqucPu37nFM',
    appId: '1:896144153617:web:354bf845f83c126b1ce5b0',
    messagingSenderId: '896144153617',
    projectId: 'transfer-2024-81cf3',
    authDomain: 'transfer-2024-81cf3.firebaseapp.com',
    storageBucket: 'transfer-2024-81cf3.appspot.com',
    measurementId: 'G-Z6V1X3EVG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6lezVGo-JYqiJe68N_xXr2YoNbiUhoOA',
    appId: '1:896144153617:android:336b96546beaad4c1ce5b0',
    messagingSenderId: '896144153617',
    projectId: 'transfer-2024-81cf3',
    storageBucket: 'transfer-2024-81cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_q2NsSsGIbJ193M9R-u_iMR_UwBy7zU',
    appId: '1:896144153617:ios:348c12ac7667b8861ce5b0',
    messagingSenderId: '896144153617',
    projectId: 'transfer-2024-81cf3',
    storageBucket: 'transfer-2024-81cf3.appspot.com',
    iosBundleId: 'com.example.transfer2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa_q2NsSsGIbJ193M9R-u_iMR_UwBy7zU',
    appId: '1:896144153617:ios:348c12ac7667b8861ce5b0',
    messagingSenderId: '896144153617',
    projectId: 'transfer-2024-81cf3',
    storageBucket: 'transfer-2024-81cf3.appspot.com',
    iosBundleId: 'com.example.transfer2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCb-LryHToHl6bBkgA8TutoqucPu37nFM',
    appId: '1:896144153617:web:8c5ac5ba7cba7e701ce5b0',
    messagingSenderId: '896144153617',
    projectId: 'transfer-2024-81cf3',
    authDomain: 'transfer-2024-81cf3.firebaseapp.com',
    storageBucket: 'transfer-2024-81cf3.appspot.com',
    measurementId: 'G-PZF3XZQZRJ',
  );

}