import 'app/models/itinerary.dart';

List<Itinerary> TODOSOSITINERARIOS = [
  Itinerary(
      id: 'kVFLWJsV2imAsvMKzW27',
      code: 'DARCY 1.V.INT',
      kilometer: 40,
      studentsId: [
        '06sWwYRJHRwvKP3cyTL4',
        '0EUFGs5hq2b1ap3xAxWR',
        '13SGW33bV5ZEm5khfVF4',
        '1LXzK1sWVz4PylMZfSKq',
        '227JKNEvs4eRflnu2xFj',
        '5XvvG8e1a4zVxwQYbXZl',
        '70CAx0X5O3Spc3KCyp8d',
        '92oZKrVY62ZUBXD1E4Zu',
        '9nWpaqAXvZSxlogblEGN',
        'CiQaIgsAXcI4JwiPagI9',
        'FOURExlqXoYFjqYRtYQ6',
        'Fb6YUxTrxl3mCVQWoghX',
        'HXSH52DtIooyan5ZaHf5',
        'IJmBwa2W8d1t0l35vdAl',
        'If7VU9u8eQG33FtEHBaA',
        'J2jjI0GTadnAa2sL4HYd',
        'JpVq6lzQIR9ZlzSwLgSI',
        'KUkPNk3OM7ohDO7a4a7D',
        'L7BmfON67rEe4g0spCam',
        'PqqMAhTQzj1cIoSDa3BM',
        'Q8jALdDmDJ1ls0QbEFgx',
        'R6yuEAJ78ACObjq1tvzC',
        'R8otY1MlTDDbG6R05GBV',
        'RmMKLHsodQkyeJzLNU2F',
        'SbTgznVMlZlaE0qPDOeX',
        'TVEweXSlzWmlDVx6bMVT',
        'U0fHzoqBJsPGO6G0kZj3',
        'XFEpylOEqkwguqv8o2Bf',
        'XYJ8WFu0VdVmE3lrwVBr',
        'cYw4ArSI28pghhBKdglq',
        'dKlNOfcv2EvEoAE8DQDa',
        'ftQi0iqvDUHfV3aB5XEF',
        'g0jGc8vyvMt3WujLhk0E',
        'hogy9foDZvMgtwzWXNer',
        'jZwkUTrht5zXViPVFBce',
        'kRzLQuoiqJaRhGsp2hZy',
        'kpXKodb6qULMizwggq22',
        'mFL1k3niFxSOWOngV07r',
        'mnZDMmL5Th2dFmCJfwow',
        'oHADwHcGPQAPbAylxvyk',
        'omJGy5lpuSo7GioLVSNZ',
        'q5nChpXcQwdzlxrGjKUA',
        'qUXU6Z42V7B84PHYG223',
        'rGy365qxMEYGzIH9bqIy',
        'st2q1MJShQBlCaqCp4kf',
        't1h0WOKL1ogYEayIQ7pd',
        'tdOW6u7qHlaFdb27I6AE',
        'ulSboBgvd3OVET36N0YF',
        'uunwX1IbPTY0kaas94te',
        'xyGVpGSfaEReCCPCLqLZ',
        'y7giBcJwThMa1uNIDq1b',
      ],
      schoolIds: [],
      importantAnnotation: '',
      appUserId: '',
      type: TypeItinerary.urban,
      contract: '20/2022',
      trajectory:
          'CED DARCY RIBEIRO / ESCOLA SUP DE DEFESA/ JARDIM BOTÂNICO DE BRASILIA/ CED DARCY RIBEIRO',
      driverName: 'DEOMIDIO SANTOS DA CONCEIÇÃO',
      driverPhone: '61992701107',
      driverLicence: '04750558207',
      capacity: 38,
      shift: 'INTEGRAL',
      vehiclePlate: 'JKP5C27'),
];
